// Mapping of country/city names to country codes for Calendarific API
export const countryMap: Record<string, string> = {
  // Cities
  'москва': 'ru',
  'moscow': 'ru',
  'санкт-петербург': 'ru',
  'st. petersburg': 'ru',
  'paris': 'fr',
  'париж': 'fr',
  'london': 'gb',
  'лондон': 'gb',
  'berlin': 'de',
  'берлин': 'de',
  'tokyo': 'jp',
  'токио': 'jp',
  'barcelona': 'es',
  'барселона': 'es',
  'rome': 'it',
  'рим': 'it',
  'amsterdam': 'nl',
  'амстердам': 'nl',
  'dubai': 'ae',
  'дубай': 'ae',
  'bangkok': 'th',
  'бангкок': 'th',
  'cairo': 'eg',
  'каир': 'eg',
  'sydney': 'au',
  'сидней': 'au',
  'new york': 'us',
  'нью-йорк': 'us',
  'los angeles': 'us',
  'лос-анджелес': 'us',
  'chicago': 'us',
  'чикаго': 'us',
  'toronto': 'ca',
  'торонто': 'ca',
  'vancouver': 'ca',
  'ванкувер': 'ca',
  'mexico city': 'mx',
  'мехико': 'mx',
  'buenos aires': 'ar',
  'буэнос-айрес': 'ar',
  'são paulo': 'br',
  'сан-паулу': 'br',
  'istanbul': 'tr',
  'стамбул': 'tr',
  'singapore': 'sg',
  'сингапур': 'sg',
  'hong kong': 'hk',
  'гонконг': 'hk',
  'seoul': 'kr',
  'сеул': 'kr',
  'shanghai': 'cn',
  'шанхай': 'cn',
  'beijing': 'cn',
  'пекин': 'cn',
  'vienna': 'at',
  'вена': 'at',
  'prague': 'cz',
  'прага': 'cz',
  'warsaw': 'pl',
  'варшава': 'pl',
  'budapest': 'hu',
  'будапешт': 'hu',
  'athens': 'gr',
  'афины': 'gr',
  'macao': 'mo',
  'макао': 'mo',
  'varna': 'bg',
  'варна': 'bg',
  'sofia': 'bg',
  'софия': 'bg',
  'bucharest': 'ro',
  'бухарест': 'ro',
  'bali': 'id',
  'бали': 'id',
  'jakarta': 'id',
  'джакарта': 'id',
  'penang': 'my',
  'пенанг': 'my',
  'kuala lumpur': 'my',
  'куала-лумпур': 'my',
  // Countries
  'russia': 'ru',
  'россия': 'ru',
  'france': 'fr',
  'франция': 'fr',
  'united kingdom': 'gb',
  'uk': 'gb',
  'англия': 'gb',
  'germany': 'de',
  'германия': 'de',
  'japan': 'jp',
  'япония': 'jp',
  'spain': 'es',
  'испания': 'es',
  'italy': 'it',
  'италия': 'it',
  'netherlands': 'nl',
  'нидерланды': 'nl',
  'united arab emirates': 'ae',
  'оаэ': 'ae',
  'thailand': 'th',
  'таиланд': 'th',
  'egypt': 'eg',
  'египет': 'eg',
  'australia': 'au',
  'австралия': 'au',
  'united states': 'us',
  'usa': 'us',
  'сша': 'us',
  'canada': 'ca',
  'канада': 'ca',
  'mexico': 'mx',
  'мексика': 'mx',
  'argentina': 'ar',
  'аргентина': 'ar',
  'brazil': 'br',
  'бразилия': 'br',
  'turkey': 'tr',
  'турция': 'tr',
  'south korea': 'kr',
  'корея': 'kr',
  'china': 'cn',
  'китай': 'cn',
  'austria': 'at',
  'австрия': 'at',
  'czech republic': 'cz',
  'чехия': 'cz',
  'poland': 'pl',
  'польша': 'pl',
  'hungary': 'hu',
  'венгрия': 'hu',
  'greece': 'gr',
  'греция': 'gr',
  'bulgaria': 'bg',
  'болгария': 'bg',
  'romania': 'ro',
  'румыния': 'ro',
  'indonesia': 'id',
  'индонезия': 'id',
  'malaysia': 'my',
  'малайзия': 'my',
};

export function getCountryCode(cityOrCountry: string): string {
  const normalized = cityOrCountry.toLowerCase().trim();
  return countryMap[normalized] || 'us'; // default to US if not found
}
